<a href="https://colab.research.google.com/github/Ashishk811/MLUP-class/blob/main/kNN_with_Iris_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/Ashishk811/MLUP-class.git

Cloning into 'MLUP-class'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (91/91), done.
Receiving objects: 100% (93/93), 245.46 KiB | 18.88 MiB/s, done.
remote: Total 93 (delta 25), reused 0 (delta 0), pack-reused 0 (from 0)
Resolving deltas: 100% (25/25), done.

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
file_path = r"/content/MLUP-class/kNN_Iris_Dataset/Iris.csv"

In [5]:
def load_iris(file_path):
    try:
        df = pd.read_csv(
            file_path,
            na_values='?',
        )

        print("\nDataset loaded successfully!")
        print(f"Shape: {df.shape}")
        print("\nFirst 5 rows:")
        print(df.head())

        missing_count = df.isnull().sum()
        if missing_count.any():
            print("\nMissing values detected:")
            print(missing_count[missing_count > 0])
        else:
            print("\nNo missing values found.")

        return df

    except Exception as e:
        print("Error loading dataset:", e)
        return None

df = load_iris(file_path)

Dataset loaded successfully!
Shape: (150, 6)

First 5 rows:
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

No missing values found.

In [6]:
df = df.drop('Id', axis=1)
print("DataFrame after deleting the 'Id' column:")
print(df.shape)
display(df.head())

DataFrame after deleting the 'Id' column:
(150, 5)

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
print("Varieties of class levels in 'Species' column and their counts:")
display(df['Species'].value_counts())

Varieties of class levels in 'Species' column and their counts:

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
from collections import Counter

In [10]:
# Features and target
X = df.iloc[:, 0:4].values   # SepalLength, SepalWidth, PetalLength, PetalWidth
y = df.iloc[:, 4].values     # Species

In [11]:
# Convert species names to numbers
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [13]:
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

In [14]:
# KNN function
def knn_predict(X_train, y_train, X_test, k=3):
    predictions = []

    for test_point in X_test:
        distances = []

        for i in range(len(X_train)):
            distance = euclidean_distance(test_point, X_train[i])
            distances.append((distance, y_train[i]))

        # Sort distances
        distances.sort(key=lambda x: x[0])

        # Get k nearest neighbors
        k_nearest = distances[:k]

        # Majority voting
        labels = [label for _, label in k_nearest]
        most_common = Counter(labels).most_common(1)
        predictions.append(most_common[0][0])

    return np.array(predictions)

In [15]:
# Predict
y_pred = knn_predict(X_train, y_train, X_test, k=3)

In [16]:
# Accuracy
accuracy = np.sum(y_pred == y_test) / len(y_test)
print("Accuracy:", accuracy)

Accuracy: 1.0